### ISSUE TITLE
there is probleme about that and i dont know what to do ?

### ISSUE THREAD

**Issue by adryserage** [ylorant/HedgeBot#1]
03/15/2016 07:42:02 PM -- Notice -- Starting HedgeBot... 
[0m03/15/2016 07:42:02 PM -- Notice -- Bootstrapping storage... 
[0m03/15/2016 07:42:02 PM -- Notice -- Loading main storages... 
[0m[0;31m03/15/2016 07:42:02 PM -- Error -- **_Cannot load storage: storage type undefined._** [0m[0;31m03/15/2016 07:42:02 PM -- Error -- Cannot load config storage. 
[0m

**Comment by ylorant** [comment]
Hello,

First, sorry for the late reply. I'm not watching this page every now and then, and the notification was drown in my notification stream. This won't happen anymore.

So your problem seems like you have no configuration storage defined. Check that your configuration is correct, especially your storage sections. They should look like this (using 2 file storages, one for the config at the config/ path, and one for the data at the data/ path) :

```
[storage.config]
type = file
basepath = conf
backups = false
readonly = true

[storage.data]
type = file
basepath = data
backups = false
```

A guide will soon be available to explain how to properly install the bot.

**Comment by adryserage** [comment]
thnaks very much for the tips am waiting after you guide ...
